flask/app.py
import sys
from instance.config import Config
from blueprints.users import users
from blueprints.visitors import visitors
from flask import Flask, redirect, url_for, session, g

# Inicia el objeto de la aplicación.
app = Flask(__name__)

# Actualiza la configuración de la aplicación.
app.config.from_object(Config)

# Este manejador se ejecuta el primero de todos ante cualquier petición.
@app.before_request
def check_session():
    '''
    session --> Cookie de sesión, está asociada a quien realiza la petición.
    g --> Es una variable especial que persiste datos hasta que acaba la petición.
    '''
    g.user = session['user'] if 'user' in session else None

# Página principal
@app.route('/', methods=['GET'])
def index():
    return redirect(url_for('visitors.signup'))

# Registramos los Blueprints
app.register_blueprint(visitors, url_prefix='/visitors')
app.register_blueprint(users, url_prefix='/users')

# Página no encontrada
@app.errorhandler(404)
def page_not_found(error):
    return 'Error 404', 404

# Error interno
@app.errorhandler(500)
def internal_server_error(error):
    return 'Error 500', 500

flask/blueprints/users.py
import datetime
from business.asUsers import asUsers
from flask import Blueprint, g, session, request, redirect, url_for, render_template

# Creamos un blueprint para exportarlo
users = Blueprint('users', __name__)

# ****************************************************************************************************************************************
# ****************************************************************************************************************************************
# ****************************************************************************************************************************************

@users.before_request
def check_logged():
    # Si el usuario no está registrado le redirigimos al inicio de sesión.
    if g.user is None: return url_for('visitors.signin')

# ****************************************************************************************************************************************
# ****************************************************************************************************************************************
# ****************************************************************************************************************************************

@users.route('/profile', methods=['GET'])
def profile():
    return render_template('profile.html', pagetitle = 'Perfil', pagename = 'Perfil de usuario'), 200

# ****************************************************************************************************************************************

@users.route('/logout', methods=['GET'])
def logout():
    # Vacía el contenido de la cookie de sesión.
    session.clear()
    # Redirige al usuario a la página de inicio de sesión.
    return redirect(url_for('visitors.signin'))

# ****************************************************************************************************************************************

@users.route('/purchases', methods=['GET', 'POST'])
def purchases():
    if request.method == 'GET':
        return render_template('purchases.html', pagetitle = 'Compras', pagename = 'Mis compras', sysdate = datetime.date.today()), 200
    elif request.method == 'POST':
        purchases = asUsers().getUserPurchasesOf(request.form.to_dict())
        return render_template('purchases.html', pagetitle = 'Compras', pagename = 'Mis compras', purchases = purchases, sysdate = datetime.date.today()), 200

# ****************************************************************************************************************************************

@users.route('/products', methods=['GET'])
def products():
    products = asUsers().getProducts()
    return render_template('products.html', pagetitle = 'Catálogo', pagename = 'Catalogo de productos', products = products), 200

@users.route('/buyProducts/<id_user>/<id>', methods=['GET'])
def buyProducts(id, id_user):
    mess = asUsers().buyProducts(request.args.to_dict(), id_user, id)
    return render_template('products_buy.html', pagetitle = "Compra realizada", pagename = mess), 200

# ****************************************************************************************************************************************
# ****************************************************************************************************************************************
# ****************************************************************************************************************************************

flask/blueprints/visitors.py
from business.asVisitors import asVisitors
from flask import Blueprint, request, redirect, url_for, render_template

# Creamos un blueprint para exportarlo
visitors = Blueprint('visitors', __name__)

@visitors.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html', pagetitle = 'Registrarse', pagename = 'Creación de nuevo usuario', message = request.args.get('message')), 200

@visitors.route('/signin', methods=['GET'])
def signin():
    return render_template('signin.html', pagetitle = 'Autentificarse', pagename = 'Inicio de sesión', message = request.args.get('message')), 200

@visitors.route('/signinadmin', methods=['GET'])
def signinadmin():
    return render_template('signinadmin.html', pagetitle = 'Autentificarse', pagename = 'Acceso para administradores', message = request.args.get('message')), 200

@visitors.route('/createUser', methods=['POST'])
def createUser():
    msg = asVisitors().createUser(request.form.to_dict())
    return redirect(url_for('visitors.signup', message = msg))

@visitors.route('/checkUser', methods=['POST'])
def checkUser():
    
    transfer = asVisitors().checkUser(request.form.to_dict())

    if transfer['ok']:
        
        return redirect(url_for('users.profile', message = transfer['message']))
    
    else:
        
        return redirect(url_for('visitors.signin', message = transfer['message']))

@visitors.route('/checkAdmin', methods=['POST'])
def checkAdmin():
    
    transfer = asVisitors().checkAdmin(request.form.to_dict())

    if transfer['ok']:
        
        return redirect(url_for('users.profile', message = transfer['message']))
    
    else:
        
        return redirect(url_for('visitors.signinadmin', message = transfer['message']))

flask/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ pagetitle }}</title>
    <link rel="stylesheet" href="/static/styles.css">
</head>
<body>

    {% block header %}{% endblock %}

    <main id="cuerpo">
        <div class="tituloSeccion">
            <h1>{{ pagename }}</h1>
        </div>
        {% block content %}{% endblock %}
        {% if message %}
        <div style="text-align: center;">
            {{ message }}
        </div>
        {% endif %}
    </main>

</body>
</html>

flask/templates/products.html
{% extends 'users_header.html' %}

{% block content %}
    <div class="contenido" style="height: 80%; overflow-y: scroll;">

        <div style="margin-top: 10px; margin-left: 10px; border: solid 1px;">
            <form action="/users/searchProduct" method="get">
                <div style="display: flex;">
                    <div style="flex-grow: 1; margin: 10px;">
                        <label>Nombre del producto:</label>
                        <input type="text" name="nombre" minlength="1" maxlength="20" required>
                    </div>
                    <div style="flex-grow: 1; margin: 10px;">
                        <input type="submit" class="boton" value="Buscar">
                    </div>
                </div>
            </form>
            <hr>
            {% if product %}
            <div>
            </div>
            {% endif %}
        </div>

        <div style="padding: 5px;">
            {% for product in products %}
            <div style="margin-top: 10px; margin-left: 10px; border: solid 1px;">
                <label>Nombre:</label> {{ product[1] }} <br>
                <label>Precio:</label> {{ product[2] }} <br>
                <label>Unidades restantes:</label> {{ product[3] }} <br>
                <label>Descripcion:</label> {{ product[4] }} <br>
                <form id="Compra" action="{{ url_for('users.buyProducts', id_user=g.user.cod, id=product[0]) }}" method="GET">
                    <div style="margin-top: 10px; margin-left: 10px;">
                        <label>Unidades</label>
                        <input type="number" class="input" name="quantity" value="0" min="0">
                        <input type="submit" class="boton" value="Comprar">
                    </div>
                </form>
            </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

flask/templates/products_buy.html
{% extends 'users_header.html' %}

{% block content %}

{% endblock %}

flask/templates/profile.html
{% extends 'users_header.html' %}

{% block content %}
    <div class="contenido">
        Bien venido a tu perfil de usuario:
    </div>
    <div class="contenido">
        <form id="formulario" action="/users/newEntry" method="post">
            <div>
                <label>Nombre:</label> {{ g.user.nombre | safe }}
            </div>
            <div>
                <label>Apellidos:</label> {{ g.user.apellidos | safe }}
            </div>
            <div>
                <label>Dirección:</label> {{ g.user.direccion | safe }}
            </div>
            <div>
                <label>Correo:</label> {{ g.user.correo | safe }}
            </div>
            <div>
                <label>Saldo:</label> {{ g.user.saldo | safe }}
            </div>
        </form>
    </div>
{% endblock %}

flask/templates/purchases.html
{% extends 'users_header.html' %}

{% block content %}
    <div class="contenido" style="height: 80%; overflow-y: scroll;">
        
        <div style="margin: 10px; padding: 10px; border: solid 1px; text-align: center;">
            <form method="post">
                <div>
                    Mostrar productos comprados desde la fecha
                    <input type="date" name="from" value="{{ sysdate }}">
                    hasta la fecha
                    <input type="date" name="to" value="{{ sysdate }}">
                </div>
                <br>
                <input type="hidden" name="uid" value="{{ g.user.cod }}">
                <input type="submit" value="Mostrar" class="centrarBoton boton">
            </form>
        </div>

        {% if purchases %}
            {% for purchase, products in purchases.items() %}
                <div class="contenido" style="margin-bottom: 10px;">
                    {% for product in products %}
                        <div style="margin-top: 10px; margin-left: 10px; border: solid 1px;">
                            <label>Nombre:</label> {{ product[2] }} <br>
                            <label>Descripción:</label> {{ product[3] }} <br>
                            <label>Precio:</label> {{ product[4] }} <br>
                            <label>Cantidad:</label> {{ product[5] }} <br>
                            <label>Sub-Total:</label> {{ product[6] }} <br>
                        </div>
                    {% endfor %}
                    <div>
                        <br>
                        Coste total del pedido: {{ products[0][1] }}
                    </div>
                </div>
            {% endfor %}
        {% endif %}

    </div>
{% endblock %}

flask/templates/signin.html
{% extends 'visitors_header.html' %}

{% block content %}
    <div class="contenido">
        <form id="formulario" action="/visitors/checkUser" method="post">
            <div>
                <label>Correo:</label>
                <input type="text" name="correo" minlength="1" maxlength="200" required>
            </div>
            <div>
                <label>Contraseña:</label>
                <input type="password" name="contraseña" minlength="8" maxlength="200" required>
            </div>
            <input type="submit" class="centrarBoton boton" value="Iniciar Sesion">
        </form>
    </div>
{% endblock %}

flask/templates/signinadmin.html
{% extends 'visitors_header.html' %}

{% block content %}
    <div class="contenido">
        <form id="formulario" action="/visitors/checkAdmin" method="post">
            <div>
                <label>Correo:</label>
                <input type="text" name="correo" minlength="1" maxlength="200" required>
            </div>
            <div>
                <label>Contraseña:</label>
                <input type="password" name="contraseña" minlength="8" maxlength="200" required>
            </div>
            <input type="submit" class="centrarBoton boton" value="Iniciar Sesion">
        </form>
    </div>
{% endblock %}

flask/templates/signup.html
{% extends 'visitors_header.html' %}

{% block content %}
    <div class="contenido">
        <form id="formulario" action="/visitors/createUser" method="post">
            <div>
                <label>Nombre:</label>
                <input type="text" name="nombre" minlength="1" maxlength="30" required>
            </div>
            <div>
                <label>Apellidos:</label> 
                <input type="text" name="apellidos" minlength="1" maxlength="40" required>
            </div>
            <div>
                <label>Direccion:</label>
                <input type="text" name="direccion" minlength="1" maxlength="200" required>
            </div>
            <div>
                <label>Correo:</label>
                <input type="text" name="correo" minlength="1" maxlength="200" required>
            </div>
            <div>
                <label>Contraseña:</label>
                <input type="password" name="contraseña" minlength="8" maxlength="200" required>
            </div>
            <input type="submit" class="centrarBoton boton" value="Registrarme">
        </form>
    </div>
{% endblock %}

flask/templates/users_header.html
{% extends 'base.html' %}

{% block header %}
    <header id="cabecera">
        <div id="titulo">
            <h1>AMAZON MAL</h1>
        </div>
        <div id="botonera">
            <a href="{{ url_for('users.profile') }}">Ver mi perfil</a>
            <a href="{{ url_for('users.products') }}">Catalogo</a>
            <a href="{{ url_for('users.purchases') }}">Mis compras</a>
            <a href="{{ url_for('users.logout') }}">Salir</a>
        </div>
    </header>
{% endblock %}

flask/templates/visitors_header.html
{% extends 'base.html' %}

{% block header %}
    <header id="cabecera">
        <div id="titulo">
            <h1>AMAZON MAL</h1>
        </div>
        <div id="botonera">
            <a href="{{ url_for('visitors.signup') }}">Registrarse</a>
            <a href="{{ url_for('visitors.signin') }}">Iniciar sesión</a>
            <a href="{{ url_for('visitors.signinadmin') }}">Administración</a>
        </div>
    </header>
{% endblock %}